blogicum/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/<int:id>/', views.post_detail, name='post_detail'),
    path('category/<slug:category_slug>/', views.category_posts, name='category_posts'),
]

blogicum/blogicum/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('pages/', include('pages.urls')),
]

blogicum/pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('about/', views.about, name='about'),
    path('rules/', views.rules, name='rules'),
]

blogicum/blog/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Location(models.Model):
    name = models.CharField(max_length=256, verbose_name='Название места')
    is_published = models.BooleanField(
        default=True,
        verbose_name='Опубликовано',
        help_text='Снимите галочку, чтобы скрыть публикацию.',
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')

    class Meta:
        verbose_name = 'местоположение'
        verbose_name_plural = 'Местоположения'


class Category(models.Model):
    title = models.CharField(max_length=256, verbose_name='Заголовок')
    description = models.TextField(verbose_name='Описание')
    slug = models.SlugField(
        unique=True,
        verbose_name='Идентификатор',
        help_text='Идентификатор страницы для URL; разрешены символы латиницы, цифры, дефис и подчёркивание.',
    )
    is_published = models.BooleanField(
        default=True,
        verbose_name='Опубликовано',
        help_text='Снимите галочку, чтобы скрыть публикацию.',
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'Категории'


class Post(models.Model):
    title = models.CharField(max_length=256, verbose_name='Заголовок')
    text = models.TextField(verbose_name='Текст')
    pub_date = models.DateTimeField(
        verbose_name='Дата и время публикации',
        help_text='Можно установить дату и время в будущем, чтобы делать отложенные публикации.',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор публикации',
    )
    location = models.ForeignKey(
        Location,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name='Местоположение',
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        verbose_name='Категория',
    )

    is_published = models.BooleanField(
        default=True,
        verbose_name='Опубликовано',
        help_text='Снимите галочку, чтобы скрыть публикацию.',
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')

    class Meta:
        verbose_name = 'публикация'
        verbose_name_plural = 'Публикации'

blogicum/pages/models.py
from django.db import models

# Create your models here.

blogicum/blog/views.py
from datetime import datetime
from django.shortcuts import render, get_object_or_404

from .models import Post, Category


def get_now_datetime():
    return datetime.now()


def index(request):
    template_name = "blog/index.html"
    post_list = Post.objects.filter(
        pub_date__lte=get_now_datetime(),
        is_published=True,
        category__is_published=True,
    ).order_by(
        'created_at'
    )[:5]
    context = {
        "post_list": post_list
    }
    return render(request, template_name, context)


def post_detail(request, id):
    template_name = "blog/detail.html"

    context = {
        "post":  get_object_or_404(Post, id=id, is_published=True, category__is_published=True, pub_date__lte=get_now_datetime())
    }
    return render(request, template_name, context)


def category_posts(request, category_slug):
    template_name = "blog/category.html"
    category = get_object_or_404(Category, slug=category_slug, is_published=True)
    post_list = Post.objects.filter(category=category, is_published=True, pub_date__lte=get_now_datetime())

    context = {
        "category": category,
        "post_list": post_list,
    }
    return render(request, template_name, context)

blogicum/pages/views.py
from django.shortcuts import render


def about(request):
    template_name = "pages/about.html"
    return render(request, template_name)


def rules(request):
    template_name = "pages/rules.html"
    return render(request, template_name)

blogicum/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <title>
      {% block title %}{% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>
  <body>
    {% include "includes/header.html" %}
    <main>
      <div class="container py-5">
      {% block content %}{% endblock %}
      </div>
    </main>
    {% include "includes/footer.html" %}   
  </body>
</html>

blogicum/templates/blog/category.html
{% extends "base.html" %}
{% block title %}
  Публикации в категории «{{ category.title }}»
{% endblock %}
{% block content %}
<h1>Публикации в категории «{{ category.title }}»</h1>
<p class="mb-5">{{ category.description }}</p>
{% for post in post_list %}
  {% if not forloop.first %}
    <hr>
  {% endif %}
  <article class="mb-5">  
    {% include "includes/post_card.html" %}
  </article>   
{% endfor %}

{% endblock %}

blogicum/templates/blog/detail.html
{% extends "base.html" %}
{% block title %}
 {{ post.title }} | {{ post.location.name }} | {{ post.pub_date|date:"d E Y" }}
{% endblock %}
{% block content %}
  <article>
    <p>{{ post.pub_date|date:"d E Y" }} | {% if post.location and post.location.is_published %}{{ post.location.name }}{% else %}Планета Земля{% endif %}<br>
      <small>От автора @{{ post.author.username }} в категории {% include "includes/category_link.html" %}</small></p>
    <h3>{{ post.title }}</h3>
    <p>{{ post.text|linebreaksbr }}</p>
  </article> 
{% endblock %}

blogicum/templates/blog/index.html
{% extends "base.html" %}
{% block title %}
  Лента записей
{% endblock %}
{% block content %}
  <h1 class="mb-5">Лента записей</h1>
  {% for post in post_list %}
    {% if not forloop.first %}
      <hr>
    {% endif %}
    <article class="mb-5">  
      {% include "includes/post_card.html" %}
    </article>   
  {% endfor %}
{% endblock %}

blogicum/templates/includes/category_link.html
<a class="text-muted" href="{% url 'blog:category_posts' post.category.slug %}">
  «{{ post.category.title }}»
</a>

blogicum/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© Блогикум</p>    
</footer>

blogicum/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'blog:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        Блогикум
      </a>
      {% with request.resolver_match.view_name as view_name %}        
      <ul class="nav  nav-pills">
        <li class="nav-item">              
          <a class="nav-link {% if view_name == 'blog:index' %} active {% endif %}" href="{% url 'blog:index' %}">
            Лента записей
          </a>
        </li>
        <li class="nav-item">              
          <a class="nav-link {% if view_name == 'pages:about' %} active {% endif %}" href="{% url 'pages:about' %}">
            О проекте
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'pages:rules' %} active {% endif %}" href="{% url 'pages:rules' %}">
            Наши правила
          </a>
        </li>
      </ul>
      {% endwith %}      
    </div>
  </nav> 
</header>

blogicum/templates/includes/post_card.html
<p>{{ post.pub_date|date:"d E Y" }} | {% if post.location and post.location.is_published %}{{ post.location.name }}{% else %}Планета Земля{% endif %}<br>
    <small>От автора @{{ post.author.username }} в категории {% include "includes/category_link.html" %}</small></p>
<h3>{{ post.title }}</h3>
<p>{{ post.text|truncatewords:10 }}</p>
<a href="{% url 'blog:post_detail' post.id %}">
    Читать полный текст
</a>

blogicum/templates/pages/about.html
{% extends "base.html" %}
{% block title %}
  О проекте
{% endblock %}
{% block content %}
  <h1>О проекте</h1>
  <p>
    Блогикум — это дом для творческих людей. Это — сообщество людей, для которых 
    нет грани между ведением блога и дружбой в социальных сетях. 
  </p>
  <p>
    Дружба и рассказы о новых, неизведанных впечатлениях — вот 
    что вы найдете на нашем ресурсе.  Миллионы блогов по различным темам. 
    Путешествия, политики, развлечения, мода, мода, литература, дизайн и все 
    другие сферы человеческой деятельности. 
  </p>
  <p>
    Творчество, разнообразие и свобода взглядов и самовыражения — 
    основные черты наших пользователей.
  </p> 
{% endblock %}

blogicum/templates/pages/rules.html
{% extends "base.html" %}
{% block title %}
  Наши правила
{% endblock %}
{% block content %}
  <h1>Наши ценности</h1>
  <p>
    <b>Cамовыражение.</b> У наших пользователей должна 
    быть возможность создать что-то своё, выразить себя, 
    свои мысли и чувства.
  </p>
  <p>
    <b>Многообразие.</b> Мы уважаем и приветствуем разные 
    мнения и культуры. Блогикум — это место, объединяющее 
    самых разных людей. Поделитесь своим уникальным взглядом на мир.  
  </p>
  <p>
    <b>Творчество.</b> Не важно, в какой области вы творите, 
    это может быть литература, дизайн, программирование. 
    Наши инструменты помогут вам раскрыть талант максимально 
    просто и комфортно.   
  </p>
  <p>
    <b>Личность.</b> Мы сохраним ваши сокровенные мысли в тайне. 
    Делитесь своей информацией только с теми, кого выбрали. 
    Как и насколько засекречивать вашу личную информацию — 
    определяете вы и только вы.  
  </p>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <title>
      {% block title %}{% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>
  <body>
    {% include "includes/header.html" %}
    <main>
      <div class="container py-5">
      {% block content %}{% endblock %}
      </div>
    </main>
    {% include "includes/footer.html" %}   
  </body>
</html>

templates/blog/category.html
{% extends "base.html" %}
{% block title %}
  Публикации в категории {{ category.title }}
{% endblock %}
{% block content %}
  <h1 class="text-center">Публикации в категории - {{ category.title }}</h1>
  <p class="col-6 offset-3 mb-5 lead text-center">{{ category.description }}</p>
  {% for post in page_obj %}
    {% if not forloop.first %}
      <hr>
    {% endif %}
    <article class="mb-5">  
      {% include "includes/post_card.html" %}
    </article>   
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}

templates/blog/detail.html
{% extends "base.html" %}
{% block title %}
  {{ post.title }} | {% if post.location %}{{ post.location.name }}{% else %}Планета Земля{% endif %} |
  {{ post.pub_date|date:"d E Y" }}
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-body">
        {% if post.image %}
          <a href="{{ post.image.url }}" target="_blank">
            <img class="border-3 rounded img-fluid img-thumbnail mb-2 mx-auto d-block" src="{{ post.image.url }}">
          </a>
        {% endif %}
        <h5 class="card-title">{{ post.title }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">
          <small>
            {% if not post.is_published %}
              <p class="text-danger">Пост снят с публикации админом</p>
            {% elif not post.category.is_published %}
              <p class="text-danger">Выбранная категория снята с публикации админом</p>
            {% endif %}
            {{ post.pub_date|date:"d E Y, H:i" }} | {% if post.location %}{{ post.location.name }}{% else %}Планета Земля{% endif %}<br>
            От автора @{{ post.author.username }} в
            категории {% include "includes/category_link.html" %}
          </small>
        </h6>
        <p class="card-text">{{ post.text|linebreaksbr }}</p>
      </div>
    </div>
  </div>
{% endblock %}

templates/blog/index.html
{% extends "base.html" %}
{% block title %}
  Лента записей
{% endblock %}
{% block content %}
  {% for post in page_obj %}
    <article class="mb-5">
      {% include "includes/post_card.html" %}
    </article>
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}

templates/blog/location_confirm_delete.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}
  Удалить локацию
{% endblock %}

{% block content %}
  <h1>Удалить запись {{ object.pk }}</h1>
  <div class="card col-4 m-3">
    <div class="card-header">
      {{ object.name }}
    </div>
    <div class="card-body">
      <!-- В форме только csrf-токен и кнопка. Никакие другие поля тут не нужны.  -->
      <form method="post">
        {% csrf_token %}
        {% bootstrap_button button_type="submit" content="Удалить" %}
      </form>
    </div>
  </div>
{% endblock content %}

templates/blog/location_detail.html
{% extends "base.html" %}

{% block title %}
  {{ object.name }}
{% endblock %}

{% block content %}
  <h1>Информация о локации</h1>
  <hr>
  <h2>{{ object.name }}</h2>
  <div class="mb-2">
    <a class="btn btn-sm text-muted" href="{% url 'blog:location_change' object.pk %}" role="button">
      Отредактировать локацию
    </a>
    <a class="btn btn-sm text-muted" href="{% url 'blog:location_delete' object.pk %}" role="button">
      Удалить локацию
    </a>
  </div>

{% endblock content %}

templates/blog/location_form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}
  {% if "/change/" in request.path %}
    Редактировать локацию
  {% else %}
    Создать локацию
  {% endif %}
{% endblock %}

{% block content %}
  {% if "/change/" in request.path %}
    <h1>Редактировать запись {{ form.instance.pk }}</h1>
  {% else %}
    <h1>Создать запись</h1>
  {% endif %}
  <div class="card col-4">
    <div class="card-header">
      Локация
    </div>
    <div class="card-body">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="Отправить" %}
      </form>
    </div>
  </div>
{% endblock content %}

templates/blog/location_list.html
{% extends "base.html" %}
{% block title %}
  Локации
{% endblock %}
{% block content %}
  {% for location in page_obj %}
    {% if not forloop.first %}
      <hr>
    {% endif %}
    <article class="mb-5">
      <h3>{{ location.name }}</h3>
      <a class="text-muted" href="{{ location.get_absolute_url }}">Посмотреть локацию</a>
    </article>
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}

templates/core/403csrf.html
{% extends "base.html" %}
{% block title %}Ошибка CSRF токена{% endblock %}
{% block content %}
  <h1>Ошибка CSRF токена. 403</h1>
  <a href="{% url 'blog:index' %}">Вернуться на главную</a>
{% endblock %}

templates/includes/category_link.html
<a class="text-muted" href="{{ post.category.get_absolute_url }}">
  «{{ post.category.title }}»
</a>

templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© Блогикум</p>    
</footer>

templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'blog:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        Блогикум
      </a>
      {% with request.resolver_match.view_name as view_name %}        
      <ul class="nav  nav-pills">
        <li class="nav-item">              
          <a class="nav-link {% if view_name == 'blog:index' %} active {% endif %}" href="{% url 'blog:index' %}">
            Лента записей
          </a>
        </li>
        <li class="nav-item">              
          <a class="nav-link {% if view_name == 'pages:about' %} active {% endif %}" href="{% url 'pages:about' %}">
            О проекте
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'pages:rules' %} active {% endif %}" href="{% url 'pages:rules' %}">
            Наши правила
          </a>
        </li>
      </ul>
      {% endwith %}      
    </div>
  </nav> 
</header>

templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            << </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            >>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

templates/includes/post_card.html
<div class="col d-flex justify-content-center">
  <div class="card" style="width: 40rem;">
    <div class="card-body">
      {% if post.image %}
        <a href="{{ post.image.url }}" target="_blank">
          <img class="border-3 rounded img-fluid img-thumbnail mb-2 mx-auto d-block" src="{{ post.image.url }}">
        </a>
      {% endif %}
      <h5 class="card-title">{{ post.title }}</h5>
      <h6 class="card-subtitle mb-2 text-muted">
        <small>
          {% if not post.is_published %}
            <p class="text-danger">Пост снят с публикации админом</p>
          {% elif not post.category.is_published %}
            <p class="text-danger">Выбранная категория снята с публикации админом</p>
          {% endif %}
          {{ post.pub_date|date:"d E Y, H:i" }} | {% if post.location %}{{ post.location.name }}{% else %}Планета Земля{% endif %}<br>
          От автора @{{ post.author.username }} в
          категории {% include "includes/category_link.html" %}
        </small>
      </h6>
      <p class="card-text">{{ post.text|truncatewords:10 }}</p>
      <a href="{{ post.get_absolute_url }}" class="card-link">Читать полный текст</a>
    </div>
  </div>
</div>

templates/pages/about.html
{% extends "base.html" %}
{% block title %}
  О проекте
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        О проекте
      </div>
      <div class="card-body">
        <p>
          Блогикум — это дом для творческих людей. Это — сообщество людей, для которых
          нет грани между ведением блога и дружбой в социальных сетях.
        </p>
        <p>
          Дружба и рассказы о новых, неизведанных впечатлениях — вот
          что вы найдете на нашем ресурсе. Миллионы блогов по различным темам.
          Путешествия, политика, развлечения, мода, литература, дизайн и все
          другие сферы человеческой деятельности.
        </p>
        <p>
          Творчество, разнообразие и свобода взглядов и самовыражения —
          основные черты наших пользователей.
        </p>
      </div>
    </div>
  </div>
{% endblock %}

templates/pages/rules.html
{% extends "base.html" %}
{% block title %}
  Наши правила
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        Правила сайта
      </div>
      <div class="card-body">
        <p>
          <b>Cамовыражение.</b> У наших пользователей должна
          быть возможность создать что-то своё, выразить себя,
          свои мысли и чувства.
        </p>
        <p>
          <b>Многообразие.</b> Мы уважаем и приветствуем разные
          мнения и культуры. Блогикум — это место, объединяющее
          самых разных людей. Поделитесь своим уникальным взглядом на мир.
        </p>
        <p>
          <b>Творчество.</b> Не важно, в какой области вы творите,
          это может быть литература, дизайн, программирование.
          Наши инструменты помогут вам раскрыть талант максимально
          просто и комфортно.
        </p>
        <p>
          <b>Личность.</b> Мы сохраним ваши сокровенные мысли в тайне.
          Делитесь своей информацией только с теми, кого выбрали.
          Как и насколько засекречивать вашу личную информацию —
          определяете вы и только вы.
        </p>
      </div>
    </div>
  </div>
{% endblock %}